/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package json.generator.demo;

import json.generator.api.Generator;
import json.generator.api.GeneratorFactory;

import java.util.Optional;

public class App {

    private Generator<String, String> generator = GeneratorFactory.getDefaultGenerator();

    public String generate(String input) {
        return generator.generate(input);
    }

    public static void main(String[] args) {
        String arg = Optional.ofNullable(args[0]).orElse("");
        System.out.println(new App().generate(arg));
    }
}
