/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package json.generator.demo;

import org.junit.jupiter.api.Named;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.params.provider.Arguments.arguments;

class AppTest {

    private static final String HELLO = """
            {"hello":"world"}""";

    private static final String NAMES = """
            {
             "firstName": "alpha",
             "lastName": "beta"
            }""";

    private static final String BOOKS = """
            [
                {
                    "genre": "reference",
                    "author": "Nigel Rees",
                    "title": "Sayings of the Century",
                    "price": 8.95
                }
            ]""";

    private static final String NESTED_JSON = """
            {
              "id": "0",
              "username": "string",
              "strings": [
                "traveling",
                "technology"
              ],
              "numbers": [1, 3],
              "nestedObject": {
                "param1": "Mahanaxar",
                "param2": "Valinor"
              },
              "firstName": "blah",
              "lastName": "blahh",
              "gender": "Unknown",
              "address": "123 St"
            }""";

    private static final String WITH_SPEC = """
            {
              "___GENERATOR_SPEC": {
                "___LOCALIZATION": {
                  "language": "en",
                  "country": "US"
                },
                "___FIELDS": [
                  {
                    "fieldName": "someStaticField",
                    "generatorName": "IDENTITY"
                  },
                  {
                    "fieldName": "generatedId",
                    "generatorName": "RANDOM_UUID"
                  },
                  {
                    "fieldName": "someOneOf",
                    "generatorName": "ONE_OF",
                    "parameters": {
                      "values": [
                        "B1",
                        "B2",
                        "AX"
                      ]
                    }
                  }
                ]
              },
              "someStaticField": "static",
              "uuid": "72ebd5b3-6109-443c-8cb3-6e3a96e7fb86",
              "id": "b66aef25-de3b-4761-8db2-b66793043aac",
              "generatedId": "2587beeb-0d79-400c-a11b-e7df2bc45c0a",
              "someOneOf": "B2",
                        
              "fullName": "ab",
              "firstName": "a",
              "lastName": "b",
              "gender": "Unknown",
                        
              "address": "123 Bond St, Paris, FR",
              "streetAddress": "123 Bond St",
              "state": "AS",
              "timeZone": "GMT",
              "city": "Paris",
                        
              "creditCardType": "Visa",
              "creditCardNumber": "1234567890123456",
              "creditCardExpiry": "12/31/2022",
                        
              "title": "t",
              "author": "",
              "genre": "Finance",
              "publisher": "RandomHouse",
                        
              "blend": "blend",
                        
              "color": "color",
              "hexColor": "#12",
                        
              "bloodGroup": "A",
                        
              "currency": "USD",
              "currencyName": "US Dollars"
            }""";

    private static final App classUnderTest = new App();

    static Stream<Arguments> jsonInputProvider() {
        return Stream.of(
                arguments(Named.of("HELLO", HELLO)),
                arguments(Named.of("NAMES", NAMES)),
                arguments(Named.of("BOOKS", BOOKS)),
                arguments(Named.of("NESTED_JSON", NESTED_JSON)),
                arguments(Named.of("WITH_SPEC", WITH_SPEC))
        );
    }

    @ParameterizedTest
    @MethodSource("jsonInputProvider")
    void appDemo(String jsonInput) {
        String generated = classUnderTest.generate(jsonInput);
        assertNotNull(generated, "app should generate a randomized json. randomizedJson=" + generated);
        System.out.println("Input::\n" + jsonInput);
        System.out.println("Output::\n" + generated);
        System.out.println("========\n");
    }

}
